import type { Metadata } from "next"
import Image from "next/image"
import { Geist } from "next/font/google"

import aedGroup from "@/public/aed-group.png"

import "./globals.css"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"]
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} antialiased`}>
                <section className="screen">
                    {children}
                    <Image src={aedGroup} alt="AED Group" className="logo" />
                </section>
            </body>
        </html>
    )
}
